defaultNamespace: argo-workflows

labels:
  argo: events

helm:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-workflows
  values:
    server:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
        - key: "node-role.kubernetes.io/etcd"
          operator: "Exists"
    controller:
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
        - key: "node-role.kubernetes.io/etcd"
          operator: "Exists"
      authMode: server
      ingress:
        enabled: true
        hosts:
        - argo.rd.localhost
      workflowNamespaces:
      - default
      - argo-events
      - argo-workflows
    workflow:
      serviceAccount:
        create: true