defaultNamespace: argo-workflows

labels:
  argo: workflows

dependsOn:
  - selector:
      matchLabels:
        aldaas: namespace

helm:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-workflows
  values:
    server:
      ingress:
        enabled: true
        hosts:
        - argo.rd.localhost
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
        - key: "node-role.kubernetes.io/etcd"
          operator: "Exists"
    controller:
      extraEnv:
      - name: DEFAULT_REQUEUE_TIME
        value: 1s
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
        - key: "node-role.kubernetes.io/etcd"
          operator: "Exists"
      workflowNamespaces:
      - aldaas
      - argo-events
      - argo-workflows
      workflowDefaults:
        spec:
          serviceAccountName: argo-workflow
    workflow:
      serviceAccount:
        create: true
        