defaultNamespace: aldaas

labels:
  aldaas: core

dependsOn:
  - selector:
      matchLabels:
        argo: events
        argo: workflows

helm:
  chart: ./
  values:
    s3:
      existingSecret: ${ .ClusterLabels.aldaas-s3-creadentials }
      host: ${ .ClusterLabels.aldaas-s3-host }
      insecure: ${ .ClusterLabels.aldaas-s3-insecure }
      prefix: ${ .ClusterLabels.aldaas-s3-prefix }
      suffix: ${ .ClusterLabels.aldaas-s3-suffix }