defaultNamespace: aldaas

labels:
  aldaas: core

dependsOn:
  - selector:
      matchLabels:
        argo: events
        argo: workflows

helm:
  chart: ./
  values:
    s3:
      existingSecret: ${ .ClusterAnnotations.aldaasS3Creadentials }
      host: ${ .ClusterAnnotations.aldaasS3Host }
      port: ${ .ClusterAnnotations.aldaasS3Port }
      insecure: ${ .ClusterAnnotations.aldaasS3Insecure }
      bucket: ${ .ClusterAnnotations.aldaasS3Bucket }
      prefix: ${ .ClusterAnnotations.aldaasS3Prefix }
      suffix: ${ .ClusterAnnotations.aldaasS3Suffix }