serviceAccountName: argo-workflow
EventBus:
  enabled: true
s3:
  existingSecret: ""
  accesskey: ""
  secretkey: ""
  host: minio.server
  port: 80
  insecure: true
  prefix: spilo/acid-database/shasum/logical_backups
  suffix: .sql.gz