# SA from argo (add some rbac) 
serviceAccountName: argo-workflow
kubectl: v1.27.9
# create argo event bus with default name in NS for aldaas
EventBus:
  enabled: true

domain: 
tunnel:
  image: ghcr.io/negashev/aldaas
  tag: latest
  port: 8080
rook:
  storageClassName: ceph-block
  volumeSnapshotClassName: ceph-block
# s3 with backups (source data for aldaas) which update every day for example 
s3:
  existingSecret: ""
  accesskey: ""
  secretkey: ""
  host: minio.server
  port: 80
  bucket: backup
  insecure: true
  prefix: spilo/acid-database/shasum/logical_backups
  suffix: .sql.gz
# database which restore from backup to saas
application:
  image: postgres
  tag: latest
  port: 5432
  storage: 10Gi
  mount: /var/lib/postgresql/data
  args:
  command:
  env:
    - name: POSTGRES_PASSWORD
      value: passw0rd
    - name: POSTGRES_USER
      value: aldaas
    - name: POSTGRES_DB
      value: my_db_name
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 1Gi
restore:
  args:
   - gunzip -c /backup.sql.gz | psql -h $ALDAAS_HOST_DAEMON -p 5432 -U $POSTGRES_USER -d $POSTGRES_DB
  command:
   - sh
   - -c
  env:
    - name: PGPASSWORD
      value: passw0rd
    - name: POSTGRES_USER
      value: aldaas
    - name: POSTGRES_DB
      value: my_db_name
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 1Gi
check:
  args:
   - psql -h $ALDAAS_HOST_DAEMON -p 5432 -U $POSTGRES_USER -d $POSTGRES_DB -c "\l"
  command:
   - sh
   - -c