apiVersion: v1
kind: Secret
metadata:
  name: aldaas-argo-workflows-server.service-account-token
  annotations:
    kubernetes.io/service-account.name: aldaas-argo-workflows-server
type: kubernetes.io/service-account-token

# get auth for argo UI
# echo "Bearer $(kubectl get -n argo-workflows secret aldaas-argo-workflows-server.service-account-token -o=jsonpath='{.data.token}' | base64 --decode)"