apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cleanup-{{ template "aldaas.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  workflowSpec:
    templates:
      - name: cleanup-backups
        inputs:
          artifacts:
            - name: kubectl
              path: /bin/kubectl
              mode: 755
              http:
                url: >-
                  https://storage.googleapis.com/kubernetes-release/release/{{ .Values.kubectl }}/bin/linux/amd64/kubectl
            - name: jq
              path: /bin/jq
              mode: 755
              http:
                url: >-
                  https://github.com/jqlang/jq/releases/download/jq-{{ .Values.jq }}/jq-linux-amd64
        container:
          name: cleanup-backups
          image: alpine
          command:
            - sh
          args:
            - /script/cleanup.sh
          resources: {}
          volumeMounts:
            - name: cleanup-script
              mountPath: /script
    volumes:
      - name: cleanup-script
        configMap:
          name: cleanup-{{ template "aldaas.fullname" . }}
    entrypoint: cleanup-backups
    arguments: {}
    ttlStrategy:
      secondsAfterCompletion: 300
    podGC:
      strategy: OnPodCompletion
  schedule: '* * * * *'