apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: minio-{{ template "aldaas.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  minio:
    backup:
      bucket:
        name: "{{ .Values.s3.bucket}}"
      endpoint: "{{.Values.s3.host}}:{{.Values.s3.port}}"
      events:
        - s3:ObjectCreated:Put
      insecure: {{.Values.s3.insecure}}
      accessKey:
        key: accesskey
        name: {{ template "s3.credentials" . }} 
      secretKey:
        key: secretkey
        name: {{ template "s3.credentials" . }} 
      filter:
        prefix: "{{.Values.s3.prefix}}"
        suffix: "{{.Values.s3.suffix}}"
