apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: s3-{{ template "aldaas.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    container:
      {{- with .Values.eventsource.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  sqs:
    backup:
      region: {{ .Values.s3.region | default "eu-central-1" }}
      queue: {{ .Values.s3.sqsQueue | default "aldaas-s3-backup-events" }}
      waitTimeSeconds: 20
      accessKey:
        key: accesskey
        name: {{ .Values.s3.sqsSecret | default "aldaas-sqs-events" }}
      secretKey:
        key: secretkey
        name: {{ .Values.s3.sqsSecret | default "aldaas-sqs-events" }}
