{{- if .Values.EventBus.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  nats:
    native:
      replicas: 3
      auth: token
      containerTemplate:
        resources:
          requests:
            cpu: "10m"
      metricsContainerTemplate:
        resources:
          requests:
            cpu: "10m"
      persistence:
        accessMode: ReadWriteOnce
        volumeSize: 10Gi
        storageClassName: {{ .Values.EventBus.storageClassName | default "ebs-csi-default-sc" }}
{{- end -}}
