apiVersion: v1
kind: ConfigMap
metadata:
  name: uptime-{{ template "aldaas.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  run.py: |
    from prometheus_client.parser import text_string_to_metric_families
    import requests
    import time
    while True:
      metrics = requests.get("http://0.0.0.0:{{ .Values.tunnel.port }}/metrics").content
      for family in text_string_to_metric_families(metrics):
        for sample in family.samples:
          print("Name: {0} Labels: {1} Value: {2}".format(*sample))
      time.sleep(5)