apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "aldaas.fullname" . }}-{{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
      - services
    verbs:
      - "*"
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "aldaas.fullname" . }}-{{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "aldaas.fullname" . }}-{{ .Values.serviceAccountName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
