apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: remove-{{ template "aldaas.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  dependencies:
    - eventName: remove
      eventSourceName: remove-{{ template "aldaas.fullname" . }}
      name: remove-dep
  template:
    serviceAccountName: {{ .Values.serviceAccountName }}
  triggers:
    - template:
        name: {{ template "aldaas.fullname" . }}-pod-remove
        k8s:
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: remove-{{ template "aldaas.fullname" . }}-
              spec:
                serviceAccountName: {{ .Values.serviceAccountName }}
                containers:
                  - name: remove-container
                    image: rancher/kubectl:{{ .Values.kubectl }}
                    command:
                      - kubectl
                    args:
                      - -n
                      - {{ .Release.Namespace }}
                      - delete
                      - --ignore-not-found=true
                      - workflows
                      - THIS_WILL_BE_REPLACED
          parameters:
            - src:
                dependencyName: remove-dep
                dataKey: body.wf
              dest: spec.containers.0.args.5