apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: remove-{{ template "aldaas.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    remove:
      port: "12000"
      endpoint: /remove
      method: POST