{{- if empty .Values.s3.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "aldaas.fullname" . }}-credentials-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  accesskey: {{ .Values.s3.accesskey }}
  secretkey: {{ .Values.s3.secretkey }}
{{- end -}}