defaultNamespace: rook-ceph

helm:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-events
  values:
    webhook:
      enabled: true
    controller:
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi